server:
  port: 8082

spring:
  application:
    name: group
  datasource:
    url: jdbc:postgresql://postgres:5432/wsgroup
    username: lemur
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    delete-dic-all: delete.dic.all
  queues:
    dic-group-queue: delete-dic-group.queue
  routing-keys:
    dic-key-all: del-dic.routing-key