server:
  port: 8086

spring:
  application:
    name: text
  data:
    mongodb:
      port: 27017
      host: mongo
      database: text
#      user: root
#      password: example
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    delete-dic-all: delete.dic.all
  queues:
    dic-text-queue: delete-dic-text.queue
  routing-keys:
    dic-key-all: del-dic.routing-key